qaenv=https://automationexercise.com/
stagenv=https://stag.freelance-learn-automation.vercel.app

retry=2

browser=firefox

pageloadtime=60

implicitwait=10

lambdahub=https://hub.lambdatest.com

lt_username=sample@gmail.com

lt_api_key=1115456145

headless=false

highlight=true

screenshot_on_failure=true

screenshot_on_success=false

screenshot_on_skip=false

incognito=false
